const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/ljm/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.FINSET_URL||'http://127.0.0.1:5173/';const browserMode=process.env.FINSET_BROWSER==='1';let browser;
const {observe,resultAfter}=require('./browser-observer.cjs');
(async()=>{
 browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:412,height:917},isMobile:true,hasTouch:true,reducedMotion:'reduce'});const errors=[],checks=[],runs=[];page.on('pageerror',e=>errors.push(e.message));if(browserMode){await observe(page);await page.route('**/api/**',r=>r.abort())}
 const b=n=>page.getByRole('button',{name:n,exact:true}),click=async l=>{await l.scrollIntoViewIfNeeded();await l.click()},next=async()=>click(b('다음')),radio=async n=>click(page.getByRole('radio',{name:n,exact:true}));
 async function layout(tag){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),tag);checks.push(tag)}
 await page.goto(base+'?screen=dashboard');await page.waitForLoadState('networkidle');const stored=await page.evaluate(()=>localStorage.getItem('finset-demo-v1'));
 async function basics({cash='0',monthly='30',goal='360',term='1년',variable=false}={}){
  await page.goto(base+'?screen=guided');await page.locator('#core-goal').fill(goal);await click(b(term));await next();
  await page.locator('#core-cash').fill(cash);await page.locator('#core-monthly').fill(monthly);
  if(monthly!=='0'){await radio(variable?'달마다 달라요':'매달 비슷해요');if(variable)await page.locator('#core-low').fill('20')}else assert.equal(await page.getByRole('radiogroup',{name:'수입이 일정한가요?'}).count(),0);
  await next();await radio('은행만 · 인터넷은행 포함');await radio('개인 생활·목표를 위한 돈');await radio('아니요');await next();await radio('없어요');await radio('네 · 쓸 돈은 빼고 입력했어요');await next();await page.locator('#core-age').fill('25');await page.getByRole('radiogroup',{name:'대한민국 국적인가요?'}).getByRole('radio',{name:'네',exact:true}).click();await page.getByRole('radiogroup',{name:'현재 한국에 살고 있나요?'}).getByRole('radio',{name:'네',exact:true}).click();
 }
 await page.goto(base+'?screen=guided');await page.locator('#core-goal').fill('500');await click(b('1년 6개월'));await next();await page.locator('#core-cash').fill('0');await click(b('30만원'));await click(b('30만원'));assert.equal(await page.locator('#core-monthly').inputValue(),'30');assert.equal(await page.locator('#core-reserve').count(),0);await layout('412x917 만원 입력');await page.locator('.core-onboarding').screenshot({path:'.qa/v16-input.png'});
 await click(b('이전'));assert.equal(await page.locator('#core-goal').inputValue(),'500');assert.equal(await b('1년 6개월').getAttribute('aria-pressed'),'true');await click(b('5년'));await next();assert.equal(await page.locator('#core-monthly').inputValue(),'30');await page.locator('#core-monthly').fill('');await next();assert.ok(await page.getByRole('alert').count());await page.locator('#core-monthly').fill('0');assert.match(await page.getByRole('status').innerText(),/모두 0원/);checks.push('목적 생략, 18개월·5년, 프리셋 교체, 빈칸≠0, 이전 답 유지, 모두 0원 조기 안내');
 await basics();await page.locator('.core-onboarding').screenshot({path:'.qa/v16-basics.png'});
 {
  async function submit(){if(browserMode)return resultAfter(page,()=>click(b('내 조건으로 비교하기')));const pending=page.waitForResponse(r=>r.url().includes('/api/v2/recommend'));await click(b('내 조건으로 비교하기'));const res=await pending;assert.equal(res.status(),200);return res.json()}
  async function finish(last,label){const requests=[];for(let i=0;i<70;i++){await page.locator('.loading-state').waitFor({state:'hidden'});const q=page.locator('[data-question]');if(!await q.count())break;const id=await q.getAttribute('data-question');const schema=last.questions.find(v=>v.id===id);assert.ok(schema,id);
    if(schema.type==='number')await q.locator('#core-answer').fill(id.includes('kakao.auto_months')?'6':'0');
    else if(schema.options?.some(o=>o.value===false))await click(q.getByRole('radio',{name:schema.options.find(o=>o.value===false).label,exact:true}));
    else if(id==='contribution_preference')await click(q.getByRole('radio',{name:schema.options.find(o=>o.value==='fixed_ok').label,exact:true}));
    else await click(q.getByRole('radio').last());
    assert.equal(await q.getAttribute('data-question'),id);if(i===0&&label==='saving'){await q.screenshot({path:'.qa/v16-question.png'})}
    if(browserMode)last=await resultAfter(page,next);else{const pending=page.waitForResponse(r=>r.url().includes('/api/v2/recommend'));await next();last=await(await pending).json()}requests.push(id);
  }await page.locator('.loading-state').waitFor({state:'hidden'});assert.equal(await page.locator('[data-question]').count(),0);assert.ok(last.result.cards.length>0);assert.ok(last.result.cards.length<=3);if(await page.locator('.core-goal-gate').count())await click(page.locator('.core-goal-gate .primary'));await page.locator('.core-products article').first().waitFor();await page.locator('.core-products article').first().screenshot({path:`.qa/v16-${label}-card.png`});assert.ok(await page.locator('.core-source-link').first().isVisible());runs.push({label,response:last,questions:requests});return last;}
  let last=await submit();assert.equal(last.profile.monthly,300000);assert.equal(last.profile.available_now,0);assert.equal(last.profile.reserve,0);last=await finish(last,'saving');await layout('412x917 실제 추천 결과');await page.setViewportSize({width:1280,height:800});await layout('1280x800 결과');await page.setViewportSize({width:360,height:800});await layout('360x800 결과');
  await click(page.locator('.core-plan-summary button').filter({hasText:'매달 더 모을 돈'}));assert.equal(await page.locator('#core-monthly').inputValue(),'30');checks.push('기본5단계와 추가 질문이 Python 추천으로 연결; 수정 입력 유지');
  await basics({cash:'500',monthly:'0',goal:'500'});last=await submit();assert.equal(last.profile.available_now,5000000);assert.equal(last.profile.monthly,0);last=await finish(last,'deposit');assert.ok(last.result.cards.every(c=>c.products.every(p=>p.kind==='deposit')));checks.push('대조: 500만원 목돈, 월0원 → 실제 예금 추천');
  await basics({goal:'500',term:'5년',variable:true});last=await submit();assert.equal(last.result.budget.monthly,200000);assert.equal(last.result.budget.horizon,60);checks.push('5년 유지, 변동월 30만원·적은달20만원 계산');
 }
 await page.goto(base+'?screen=guided');await page.locator('#core-goal').fill('360');await click(b('1년'));await next();await page.locator('#core-cash').fill('500');await page.locator('#core-monthly').fill('0');await next();await radio('은행만 · 인터넷은행 포함');await radio('개인 생활·목표를 위한 돈');await radio('아니요');await next();await radio('있어요');assert.ok(await page.locator('.core-holdings').isVisible());await radio('아직 확인하지 못했어요');await radio('중간에 꺼낼 예정이에요');assert.match(await page.getByRole('status').innerText(),/중간에 쓸 돈/);await click(b('저축할 금액 수정하기'));assert.equal(await page.locator('#core-cash').inputValue(),'500');checks.push('보유 있음에만 상세입력; 미확인 선택, 중간 사용 시 금액 수정');
 const nav=page.locator('.mobile-nav');assert.equal(await nav.getByRole('button').count(),5);await click(nav.getByRole('button',{name:'우대조건',exact:true}));await layout('모바일 하단 우대조건 5개 메뉴');assert.equal(await page.evaluate(()=>localStorage.getItem('finset-demo-v1')),stored);assert.deepEqual(errors,[]);
 fs.writeFileSync(`.qa/v16-${browserMode?'browser':'local'}-audit.json`,JSON.stringify({base,checks,errors,runs},null,2));console.log(JSON.stringify({checks,errors,runs:runs.map(r=>({label:r.label,status:r.response.result.status,total:r.response.result.cards[0].goal_total}))},null,2));await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1)});
