const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/ljm/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.FINSET_URL||'http://127.0.0.1:4173/finset/';let browser;
(async()=>{
  fs.mkdirSync('.qa',{recursive:true});const errors=[],failures=[],requests=[],checks=[];
  browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1280,height:800},reducedMotion:'reduce'});
  page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push([r.status(),r.url()])});page.on('request',r=>requests.push(r.url()));
  const b=name=>(name==='우대조건 확인'?page.locator('.guided-flow'):page).getByRole('button',{name,exact:true});
  const amount=()=>page.getByLabel('매달 얼마까지 저축할 수 있나요?');
  const first=()=>page.locator('.quick-products .product-card').first();
  const stored=()=>page.evaluate(()=>({...localStorage}));
  const shot=async(name)=>{await page.evaluate(async()=>{await document.fonts.ready;scrollTo({top:0,behavior:'instant'});await new Promise(requestAnimationFrame)});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name+' overflow');await page.screenshot({path:`.qa/guided-${name}.png`})};
  const chooseGoal=async(name)=>page.getByRole('group',{name:'무엇을 위해 모으나요?'}).getByRole('button',{name:new RegExp(name)}).click();
  const answer=async(name)=>page.locator('.quick-transfer-options').getByRole('button',{name:new RegExp(name)}).click();
  await page.goto(base,{waitUntil:'networkidle'});await b('시연 시작').waitFor();await shot('welcome-web');
  assert.deepEqual(await stored(),{});
  await page.evaluate(()=>{localStorage.setItem('finset-demo-v1','{"preserve":"original records"}');localStorage.setItem('finset-drafts-v1','[]')});const preserved=await stored();
  await b('시연 시작').click();await shot('goal-web');assert.equal(await amount().inputValue(),'');await b('우대조건 확인').click();await page.getByRole('alert').waitFor();
  await chooseGoal('일단 모으기');await amount().fill('170000');await b('+3만').click();await b('+3만').click();await b('+1만').click();assert.equal(await amount().inputValue(),'240000');await b('−1만').click();assert.equal(await amount().inputValue(),'230000');await b('초기화').click();assert.equal(await amount().inputValue(),'');
  await amount().fill('171237');await b('우대조건 확인').click();await shot('bonus-web');await answer('직접 넣을게요');await first().waitFor();assert.equal(await first().locator('h3').innerText(),'코드K 자유적금');await shot('results-base-web');
  assert.ok((await page.locator('.result-context').innerText()).includes('171,237원'));assert.equal(await page.getByRole('dialog').count(),0);assert.equal(await page.getByRole('button',{name:/저장|초안/}).count(),0);
  await b('가능해요').click();assert.equal(await first().locator('h3').innerText(),'카카오뱅크 자유적금');assert.ok((await first().innerText()).includes('3.85%'));assert.ok((await first().innerText()).includes('조건 이행 시'));await shot('results-bonus-web');
  await b('아직 모르겠어요').click();assert.equal(await first().locator('h3').innerText(),'코드K 자유적금');await page.getByRole('status').filter({hasText:'모르는 우대'}).waitFor();assert.ok((await page.locator('.product-card').filter({hasText:'카카오뱅크 자유적금'}).innerText()).includes('3.65%'));
  checks.push('Direct 171,237-won input and repeated +10k/+30k increments work; one bonus answer immediately changes ranking; unknown never earns bonus; no save step');
  await b('금액·목표 수정').click();assert.equal(await amount().inputValue(),'171237');await chooseGoal('여행 자금');await page.getByText('목표 금액 변경 · 3,000,000원',{exact:true}).click();await page.getByLabel('목표 금액',{exact:true}).fill('3100000');await page.getByText('목표 금액 변경 · 3,100,000원',{exact:true}).click();await b('추천 다시 계산').click();await page.locator('.quick-gap').waitFor();await b('월 30만원으로 비교').click();assert.equal(await page.locator('.quick-gap').count(),0);
  assert.deepEqual(await stored(),preserved);await b('처음부터 시연 시작').click();assert.equal(await amount().inputValue(),'');assert.deepEqual(await stored(),preserved);
  checks.push('Custom goal, immediate shortage alternatives and edit/recalculate work; original browser records remain byte-for-byte unchanged');
  await page.setViewportSize({width:412,height:917});await chooseGoal('일단 모으기');await amount().fill('170000');await shot('goal-app');await b('우대조건 확인').click();await shot('bonus-app');await answer('가능해요');await shot('results-bonus-app');
  await first().getByText('추천 근거·금리 자세히 보기',{exact:true}).click();await shot('product-detail-app');await b('금액·목표 수정').click();await amount().fill('300001');await b('60개월').click();await b('추천 다시 계산').click();assert.ok(!(await page.locator('.quick-products').innerText()).includes('코드K 자유적금'));await first().getByText('추천 근거·금리 자세히 보기',{exact:true}).click();await first().getByText(/재예치 이자는 포함하지/).waitFor();await shot('results-long-app');
  await b('금액·목표 수정').click();await amount().fill('3000001');await b('추천 다시 계산').click();await page.getByRole('heading',{name:'이 금액에 맞는 상품이 없어요'}).waitFor();assert.equal(await page.locator('.product-card').count(),0);await b('월 저축액 조정하기').click();await amount().fill('0');await b('추천 다시 계산').click();await page.getByRole('alert').waitFor();
  checks.push('412×917 complete flow; 300,001 excludes capped Code K; 60-month projections disclose post-maturity principal; out-of-range amounts show a useful empty state');
  await page.reload({waitUntil:'networkidle'});await b('시연 시작').click();assert.equal(await amount().inputValue(),'');assert.deepEqual(await stored(),preserved);
  await page.evaluate(()=>localStorage.clear());
  for(const screen of ['dashboard','plan','products','conditions','recovery']){await page.goto(`${base}?screen=${screen}`,{waitUntil:'networkidle'});for(const size of [{width:1280,height:800},{width:412,height:917},{width:360,height:800}]){await page.setViewportSize(size);await shot(`${screen}-${size.width}`)}}
  await page.setViewportSize({width:1280,height:800});await page.goto(`${base}preview.html`,{waitUntil:'networkidle'});const frame=page.frameLocator('iframe');assert.deepEqual(await frame.locator('body').evaluate(()=>[innerWidth,innerHeight]),[1280,800]);await b('시연 시작 →').click();await frame.getByLabel('매달 얼마까지 저축할 수 있나요?').waitFor();await b('앱 · 412 × 917').click();assert.deepEqual(await frame.locator('body').evaluate(()=>[innerWidth,innerHeight]),[412,917]);await frame.getByLabel('매달 얼마까지 저축할 수 있나요?').fill('170000');await b('시연 시작 →').click();await frame.getByLabel('매달 얼마까지 저축할 수 있나요?').waitFor();assert.equal(await frame.getByLabel('매달 얼마까지 저축할 수 있나요?').inputValue(),'');
  checks.push('Reload clears only in-memory demo answers; main gallery screens fit 1280/412/360 widths; preview dimensions and restart work');
  assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);if(base.includes('/finset/'))assert.equal(requests.some(u=>new URL(u).pathname.startsWith('/api/')),false);
  const result={passed:true,base,checkedAt:new Date().toISOString(),checks,errors,failures};fs.writeFileSync('.qa/guided-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exit(1)});
