import { useEffect, useRef, useState } from 'react'
import { Check, ChevronLeft, ArrowRight } from 'lucide-react'
import { addMonths, money } from './model'
import { basicProfile, basicStages, basicStop, freshBasicPlan, fromManwon, validWon, validateBasic } from './basicPlan'
import type { BasicPlan } from './basicPlan'
import type { CoreMeta, CoreProfile } from './coreApi'
import { RecommendationJourney } from './CoreResults'

function Amount({ id, label, value, change, monthly = false, goal = false, hint }: { id: string; label: string; value: string; change: (v: string) => void; monthly?: boolean; goal?: boolean; hint?: string }) {
  const [raw, setRaw] = useState(value === '' ? '' : String(Number(value) / 10000))
  useEffect(() => { if (value === '' || validWon(value)) setRaw(value === '' ? '' : String(Number(value) / 10000)) }, [value])
  return <div className="core-money"><label htmlFor={id}>{label}</label>{hint && <p className="core-help" id={`${id}-help`}>{hint}</p>}<div className="money-input"><input id={id} type="text" inputMode="numeric" value={raw} placeholder="만원 단위로 입력" aria-describedby={`${id}-help ${id}-unit`} aria-invalid={value !== '' && !validWon(value)} onChange={e => { const v = e.target.value.replaceAll(',', ''); setRaw(v); change(fromManwon(v) ?? 'invalid') }}/><span>만원</span></div><p id={`${id}-unit`} className="core-amount-confirm">만원 단위 정수 · {validWon(value) ? `${money(Number(value) / 10000)}만원 (${money(Number(value))}원)` : value === '' ? '직접 입력하거나 금액을 선택해 주세요.' : '소수점·음수 없이 0~100,000만원으로 입력해 주세요.'}</p><div className="core-amount-presets">{(monthly ? [0, 5, 10, 20, 30, 50] : goal ? [100, 300, 500, 1000] : [0, 100, 300, 500, 1000]).map(n => <button key={n} type="button" className={value === String(n * 10000) ? 'selected' : ''} aria-pressed={value === String(n * 10000)} onClick={() => change(String(n * 10000))}>{n === 0 ? '없어요 · 0원' : `${n}만원`}{value === String(n * 10000) && <Check size={15}/>}</button>)}</div></div>
}
function Choice({ label, value, change, options }: { label: string; value: string; change: (v: string) => void; options: [string, string][] }) {
  return <fieldset className="basic-choice"><legend>{label}</legend><div className="quick-transfer-options" role="radiogroup" aria-label={label}>{options.map(([v, title]) => <button type="button" key={v} role="radio" aria-checked={value === v} onClick={() => change(v)}><span>{title}</span>{value === v ? <Check size={18}/> : <span className="core-radio"/>}</button>)}</div></fieldset>
}
type Row = { bank: string; product: string; balance: string }
const yn: [string,string][] = [['yes', '네'], ['no', '아니요']]
export function CoreOnboarding({ meta, visible, edit, complete, exit, home, busy, error }: { meta: CoreMeta; visible: boolean; edit: { step: number; revision: number }; complete: (p: CoreProfile) => void; exit: () => void; home: () => void; busy: boolean; error: string }) {
  const [f, setF] = useState(freshBasicPlan), [step, setStep] = useState(0), [localError, setLocalError] = useState('')
  const [mode, setMode] = useState('period'), [period, setPeriod] = useState(''), [other, setOther] = useState(false)
  const [rows, setRows] = useState<Row[]>([{ bank: '', product: '', balance: '' }]), [heldComplete, setHeldComplete] = useState(false)
  const [debtReview, setDebtReview] = useState(false)
  const heading = useRef<HTMLHeadingElement>(null)
  useEffect(() => { if (visible) { setStep(edit.step); setLocalError('') } }, [edit.revision])
  useEffect(() => { if (visible && !debtReview) { heading.current?.focus({ preventScroll: true }); window.scrollTo({ top: 0, behavior: 'instant' }) } }, [step, visible, debtReview])
  const set = (key: keyof BasicPlan, value: string) => { setF(f => ({ ...f, [key]: value })); setLocalError('') }
  const stop = basicStop(step, f)
  const debtRoute = step === 2 && f.fund === 'personal' && f.debt === 'yes'
  const debtHeading = useRef<HTMLHeadingElement>(null)
  useEffect(() => { if (debtReview) { debtHeading.current?.focus(); window.scrollTo({top: 0, behavior: 'instant'}) } }, [debtReview])
  const changeRow = (index: number, patch: Partial<Row>) => { setRows(rows.map((r, i) => i === index ? { ...r, ...patch } : r)); setHeldComplete(false); setLocalError('') }
  const next = () => {
    if (debtRoute && f.sector) { setDebtReview(true); setLocalError(''); return }
    const message = validateBasic(step, f)
    if (message) { setLocalError(message); return }
    if (step === 3 && f.holdings === 'yes' && (!heldComplete || rows.some(r => !r.bank || !validWon(r.balance)))) { setLocalError('보유 금융기관과 잔액을 확인해 주세요. 모르면 아직 확인하지 못했어요를 선택할 수 있어요.'); return }
    if (step < 4) { setStep(step + 1); setLocalError(''); return }
    const balances: Record<string, number> = {}, products: Record<string, number> = {}, facts: Record<string, number> = {}
    if (f.holdings === 'yes') for (const row of rows) { balances[row.bank] = (balances[row.bank] || 0) + Number(row.balance); if (row.product) { products[row.product] = (products[row.product] || 0) + Number(row.balance); const k = `held_count.${row.product}`; facts[k] = (facts[k] || 0) + 1 } }
    complete(basicProfile(f, { holdings_complete: f.holdings !== 'unknown', bank_balances_complete: f.holdings !== 'unknown', bank_balances: balances, held_product_ids: Object.keys(products), product_balances: products, facts }))
  }
  if (debtReview && visible) return <section className="card debt-review" aria-labelledby="debt-review-title"><p className="core-help">저축 전 잠깐 확인</p><h2 ref={debtHeading} tabIndex={-1} id="debt-review-title">대출 상환 계획부터 확인해 주세요</h2><p>대출이 있다는 이유만으로 저축을 못 하는 것은 아니에요. 지금은 먼저 갚을지 살펴볼 대출이 있다고 답해 주셨어요.</p><ul><li>대출 금리와 매달 갚을 금액</li><li>먼저 갚을 때 드는 수수료</li><li>생활비와 갚을 돈을 빼고 남는 저축 여력</li></ul><p>이 정보가 확인되기 전에는 저축이 더 유리하다고 판단하거나 상품을 확정하지 않아요.</p><div className="debt-actions"><button type="button" className="primary" onClick={() => {setDebtReview(false);setStep(1);setLocalError('')}}>저축할 금액 다시 보기</button><button type="button" className="secondary" onClick={() => {setDebtReview(false);setLocalError('')}}>대출 답변 다시 보기</button><button type="button" className="secondary" onClick={home}>홈으로</button></div><p className="core-help">금액·답변을 다시 보는 동안 입력은 유지돼요. 진행하려고 사실과 다른 답을 고를 필요는 없어요.</p></section>
  return <div hidden={!visible} className="core-onboarding"><RecommendationJourney current={step === 0 ? 0 : 1}/><div className="basic-progress" aria-label="기본 질문 진행 상황"><strong>{step + 1} / 5단계 · {basicStages[step]}</strong><progress max={5} value={step} aria-label={`기본 질문 ${step}개 완료, 현재 ${step + 1}번째 질문`}/><small>{step} / 5단계 완료 · 지금 답하는 단계는 {step + 1}번째예요.</small></div><form className="card core-input" onSubmit={e => { e.preventDefault(); next() }}><h2 ref={heading} tabIndex={-1}>{basicStages[step]}</h2>
    {step === 0 && <><Choice label="무엇을 위해 모으나요? · 선택" value={f.purpose} change={v => set('purpose', v)} options={['여행', '주거 준비', '목돈 마련', '직접 정하기', '아직 정하지 않았어요'].map(v => [v, v])}/>{f.purpose === '직접 정하기' && <label className="core-date-label">목표 이름 · 선택<input value={f.customPurpose || ''} maxLength={40} onChange={e => set('customPurpose', e.target.value)} placeholder="예: 내년 여행 준비"/></label>}<Amount id="core-goal" label="얼마를 모으고 싶나요?" goal value={f.goal} change={v => set('goal', v)}/><Choice label="모을 기간을 정해 주세요" value={mode} change={v => { setMode(v); if (v === 'period' && period) set('date', addMonths(f.start, Number(period))) }} options={[[ 'period', '기간으로 고를게요' ], [ 'exact', '꼭 필요한 날짜가 있어요' ]]}/>{mode === 'period' ? <><div className="core-amount-presets" role="group" aria-label="모을 기간">{[6, 12, 18, 24, 36, 60].map(n => <button type="button" key={n} aria-pressed={!other && period === String(n)} className={!other && period === String(n) ? 'selected' : ''} onClick={() => { setOther(false); setPeriod(String(n)); set('date', addMonths(f.start, n)) }}>{n === 18 ? '1년 6개월' : n < 12 ? `${n}개월` : `${n / 12}년`}</button>)}<button type="button" aria-pressed={other} onClick={() => setOther(true)}>다른 기간</button></div>{other && <label className="core-date-label">다른 저축 기간<select value={period} onChange={e => { setPeriod(e.target.value); set('date', addMonths(f.start, Number(e.target.value))) }}><option value="">기간 선택</option>{Array.from({ length: 120 }, (_, i) => <option key={i} value={i + 1}>{i + 1}개월</option>)}</select></label>}</> : <label className="core-date-label">이 돈이 꼭 필요한 날<input type="date" value={f.date} min={f.start} max={addMonths(f.start, 120)} onChange={e => set('date', e.target.value)}/></label>}{f.date && <p className="core-help">{f.start}부터 {f.date}까지 모아요. 목표일과 상품 만기는 각각 비교해요.</p>}<details className="core-extra"><summary>오늘 말고 다른 날 시작하나요?</summary><label className="core-date-label">모으기 시작할 날<input type="date" value={f.start} onChange={e => { const start = e.target.value; setF(p => ({ ...p, start, date: mode === 'period' && period && start ? addMonths(start, Number(period)) : p.date })) }}/></label></details></>}
    {step === 1 && <><Amount id="core-cash" label="지금 맡겨둘 수 있는 돈은 얼마인가요?" value={f.cash} change={v => set('cash', v)} hint="생활비와 곧 쓸 돈을 빼고, 정한 기간 동안 맡길 수 있는 돈이에요. 만기되어 받은 돈도 포함할 수 있어요."/><Amount id="core-monthly" label="매달 무리 없이 모을 수 있는 돈은요?" monthly value={f.monthly} change={v => set('monthly', v)} hint="생활비·갚을 돈·기존 저축을 빼고 더 모을 수 있는 금액이에요. 목돈만 맡긴다면 0원을 골라요."/>{Number(f.monthly) > 0 && <Choice label="수입이 일정한가요?" value={f.income} change={v => set('income', v)} options={[[ 'steady', '매달 비슷해요' ], [ 'variable', '달마다 달라요' ], [ 'none', '정기적인 수입이 없어요' ]]}/>} {Number(f.monthly) > 0 && f.income === 'variable' && <Amount id="core-low" label="수입이 적은 달에도 모을 수 있는 돈은요?" monthly value={f.low} change={v => set('low', v)}/>}<p className="core-help">쓸 돈을 제외하고 입력한 금액으로 비교해요. 비상금과 예정 지출을 다시 빼지 않아요.</p></>}
    {step === 2 && <><Choice label="어디까지 비교할까요?" value={f.sector} change={v => set('sector', v)} options={[[ 'bank', '은행만 · 인터넷은행 포함' ], [ 'all', '저축은행·신협도 포함' ]]}/><p className="core-help">카카오뱅크·케이뱅크·토스뱅크도 은행에 포함돼요.</p><Choice label="이번에 맡길 돈은 어떤 용도인가요?" value={f.fund} change={v => set('fund', v)} options={[[ 'personal', '개인 생활·목표를 위한 돈' ], [ 'business', '사업 운영에 쓰는 돈' ]]}/><Choice label="저축보다 먼저 갚을지 확인이 필요한 대출이 있나요?" value={f.debt} change={v => set('debt', v)} options={[["yes", "네 · 먼저 확인할게요"], ["no", "아니요 · 상환 계획을 고려한 여유자금이에요"]]}/><p className="core-help">대출 보유 여부 자체를 묻는 질문이 아니에요. 생활비와 갚을 돈을 제외한 저축 여력을 확인해요.</p></>}
    {step === 3 && <><Choice label="이미 가입한 예·적금이나 은행에 맡긴 다른 돈이 있나요?" value={f.holdings} change={v => set('holdings', v)} options={[[ 'no', '없어요' ], [ 'yes', '있어요' ], [ 'unknown', '아직 확인하지 못했어요' ]]}/>{f.holdings === 'yes' && <div className="core-holdings"><p>이번에 맡길 돈을 제외한 잔액을 원 단위로 입력해 주세요. 기존 상품을 해지해 생길 돈은 더하지 않아요.</p>{rows.map((row, i) => <fieldset key={i}><legend>보유 계좌 {i + 1}</legend><label>금융기관<select value={row.bank} onChange={e => changeRow(i, { bank: e.target.value, product: '' })}><option value="">선택</option>{meta.banks?.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>상품<select value={row.product} onChange={e => changeRow(i, { product: e.target.value })}><option value="">입출금 등 목록 외 상품</option>{meta.holdings_products?.filter(p => p.bank === row.bank).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>현재 원금과 이자 합계 · 원<input inputMode="numeric" value={row.balance} onChange={e => changeRow(i, { balance: e.target.value.replaceAll(',', '') })}/></label>{rows.length > 1 && <button type="button" onClick={() => { setRows(rows.filter((_, j) => i !== j)); setHeldComplete(false) }}>계좌 삭제</button>}</fieldset>)}<button type="button" className="secondary" onClick={() => { setRows([...rows, { bank: '', product: '', balance: '' }]); setHeldComplete(false) }}>계좌 추가</button><label className="basic-held-check"><input type="checkbox" checked={heldComplete} onChange={e => setHeldComplete(e.target.checked)}/>보유 계좌와 잔액을 모두 확인했어요</label></div>}<Choice label="입력한 돈을 정한 기간 동안 저축할 수 있나요?" value={f.withdraw} change={v => set('withdraw', v)} options={[[ 'none', '네 · 쓸 돈은 빼고 입력했어요' ], [ 'possible', '중간에 꺼내야 할 수도 있어요' ], [ 'certain', '중간에 꺼낼 예정이에요' ]]}/><p className="core-help">새 상품 가입을 비교해요. 같은 계약의 자동연장은 기존 계약에서 확인해 주세요.</p></>}
    {step === 4 && <><label className="core-number-label" htmlFor="core-age">만 나이 · 세</label><div className="money-input"><input id="core-age" inputMode="numeric" value={f.age} onChange={e => set('age', e.target.value)}/><span>세</span></div><Choice label="대한민국 국적인가요?" value={f.citizen} change={v => set('citizen', v)} options={yn}/><Choice label="현재 한국에 살고 있나요?" value={f.resident} change={v => set('resident', v)} options={yn}/></>}
    {stop && <section className="notice" role="status"><p>{stop}</p>{step === 3 && <button type="button" className="secondary" onClick={() => setStep(1)}>저축할 금액 수정하기</button>}</section>}{(localError || error) && (!stop || debtRoute) && <p className="form-error" role="alert">{localError || error}</p>}<div className="form-footer"><button type="button" className="secondary" onClick={() => step === 0 ? exit() : (setStep(step - 1), setLocalError(''))}><ChevronLeft size={17}/>이전</button><button className="primary" disabled={busy || (Boolean(stop) && !debtRoute)}>{debtRoute ? '상환 확인 안내 보기' : step === 4 ? '내 조건으로 비교하기' : '다음'}<ArrowRight size={17}/></button></div></form></div>
}
